# Generated by Django 4.1 on 2023-03-28 17:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pojistenec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jmeno",
                    models.CharField(
                        help_text="Zadejte křestní jméno pojištěnce",
                        max_length=30,
                        verbose_name="Jméno",
                    ),
                ),
                (
                    "prijmeni",
                    models.CharField(
                        help_text="Zadejte příjmení pojištěnce",
                        max_length=30,
                        verbose_name="Příjmení",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "telefon",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("ulice", models.CharField(max_length=30)),
                ("cislo_popisne", models.IntegerField(verbose_name="Číslo popisné")),
                ("mesto", models.CharField(max_length=30, verbose_name="Město")),
                (
                    "psc",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(10000),
                            django.core.validators.MaxValueValidator(99999),
                        ],
                        verbose_name="PSČ",
                    ),
                ),
            ],
            options={
                "ordering": ["prijmeni", "jmeno", "mesto"],
            },
        ),
        migrations.CreateModel(
            name="TypPojisteni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jmeno",
                    models.CharField(max_length=30, verbose_name="Typ pojištění"),
                ),
            ],
            options={
                "ordering": ["jmeno"],
            },
        ),
        migrations.CreateModel(
            name="Pojisteni",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unikátní ID pojištění",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("castka", models.IntegerField(verbose_name="Částka")),
                (
                    "mesicni_pojistne",
                    models.IntegerField(verbose_name="Měsíční pojistné"),
                ),
                ("platnost_od", models.DateField()),
                ("platnost_do", models.DateField()),
                (
                    "predmet_pojisteni",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Předmět pojištění",
                    ),
                ),
                (
                    "pojistenec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pojisteniapp.pojistenec",
                    ),
                ),
                (
                    "typ_pojisteni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="pojisteniapp.typpojisteni",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "pojistenec__prijmeni",
                    "pojistenec__jmeno",
                    "pojistenec__mesto",
                    "typ_pojisteni__jmeno",
                ],
            },
        ),
    ]
