# Generated by Django 4.1 on 2023-03-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pojisteniapp", "0002_alter_pojisteni_castka_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pojisteni",
            name="castka",
            field=models.IntegerField(verbose_name="Částka"),
        ),
    ]
