# Generated by Django 4.1 on 2023-03-29 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pojisteniapp", "0004_alter_pojistenec_jmeno_alter_pojistenec_prijmeni"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pojisteni",
            name="pojistenec",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pojisteniapp.pojistenec",
                verbose_name="Pojištěnec",
            ),
        ),
        migrations.AlterField(
            model_name="pojisteni",
            name="typ_pojisteni",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="pojisteniapp.typpojisteni",
                verbose_name="Typ pojištění",
            ),
        ),
    ]
